services:
  node-red:
    container_name: nodered
    image: nodered/node-red:latest
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - /portainer/Files/AppData/Config/nodered:/data
networks:
  node-red-net:
